package com.iap.ac.android.acs.plugin.utils;

import com.iap.ac.android.acs.plugin.interceptor.BaseInterceptor;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4RegionRpc;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4apDisableJSAPI;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4chooseCity;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4exitApp;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4getAppToken;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4getAuthCode;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4getComponentAuth;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4getOpenUserInfo;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4getPaymentCode;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4getPhoneNumber;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4getServerTime;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4getSetting;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4getSiteInfo;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4inquireQuote;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4isInstalledApp;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4navigateToBizScene;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4openSchemeWithBacking;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4paySignCenter;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4rpc;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4scan;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4signContract;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4startApp;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4thirdPartyAuthForAc;
import com.iap.ac.android.acs.plugin.interceptor.Interceptor4uploadApdidToken;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Constants {
    public static final String ACTION_CHOOSE_CITY = "com.iap.ac.android.acs.plugin.action.CHOOSE_CITY";
    public static final String ACTION_GET_PHONE_NUMBER = "com.iap.ac.android.acs.plugin.action.GET_PHONE_NUMBER";
    public static final String ACTION_THIRD_PARTY_AUTH_FOR_AC = "com.iap.ac.android.acs.plugin.action.THIRD_PARTY_AUTH_FOR_AC";
    public static final String AC_BIZ_CODE = "ac_biz";
    public static final String BIZ_CODE_FOR_REGION = "region_biz";
    public static final String JS_API_APPX_RPC = "appxrpc";
    public static final String JS_API_AP_DISABLE_JSAPI = "apDisableJSAPI";
    public static final String JS_API_CHOOSE_CITY = "chooseCity";
    public static final String JS_API_EXIT_APP = "exitApp";
    public static final String JS_API_GET_APP_TOKEN = "getAppToken";
    public static final String JS_API_GET_AUTH_CODE = "getAuthCode";
    public static final String JS_API_GET_COMPONENT_AUTH = "getComponentAuth";
    public static final String JS_API_GET_OPEN_USER_INFO = "getOpenUserInfo";
    public static final String JS_API_GET_PAYMENT_CODE = "getPaymentCode";
    public static final String JS_API_GET_PHONE_NUMBER = "getPhoneNumber";
    public static final String JS_API_GET_SERVER_TIME = "getServerTime";
    public static final String JS_API_GET_SETTING = "getSetting";
    public static final String JS_API_GET_SITE_INFO = "getSiteInfo";
    public static final String JS_API_INQUIRE_QUOTE = "inquireQuote";
    public static final String JS_API_IS_INSTALLED_APP = "isInstalledApp";
    public static final List<String> JS_API_LIST = new ArrayList();
    public static final String JS_API_NAVIGATE_TO_BIZ_SCENE = "navigateToBizScene";
    public static final String JS_API_OPEN_SCHEME_WITH_BACKING = "openSchemeWithBacking";
    public static final String JS_API_PAY_SIGN_CENTER = "paySignCenter";
    public static final String JS_API_REGION_RPC = "APRegionRPC";
    public static final String JS_API_RPC = "rpc";
    public static final String JS_API_SCAN = "scan";
    public static final String JS_API_SIGN_CONTRACT = "signContract";
    public static final String JS_API_START_APP = "startApp";
    public static final String JS_API_START_BIZ_SERVICE = "startBizService";
    public static final String JS_API_THIRD_PARTY_AUTH_FOR_AC = "thirdPartyAuthForAc";
    public static final String JS_API_TRADE_PAY = "tradePay";
    public static final String JS_API_UPLOAD_APDID_TOKEN = "uploadApdidToken";
    public static final Map<String, Class<? extends BaseInterceptor>> JS_INTERCEPTOR_MAP = new HashMap();
    public static final String KEY_AC_PARAMS = "acParams";
    public static final String KEY_AUTH_CODE = "authCode";
    public static final String KEY_AUTH_RESULT_CODE = "authResultCode";
    public static final String KEY_AUTH_STATE = "authState";
    public static final String KEY_CITY_CODE = "cityCode";
    public static final String KEY_CITY_NAME = "cityName";
    public static final String KEY_FLAG_REGION_TINYAPP = "isRegion";
    public static final String KEY_IS_NOT_REGION_TINYAPP = "NO";
    public static final String KEY_IS_REGION_TINYAPP = "YES";
    public static final String KEY_PHONE_NUMBER = "phoneNumber";
    public static final String KEY_REGION_CODE = "regionCode";
    public static final String PRESET_CONFIG_FILE_EXTENSION = ".json";
    public static final String PRESET_CONFIG_FILE_NAME = "iapconnect_config";
    public static final String SECTION_KEY_BLACK_LIST = "blackList";
    public static final String SECTION_KEY_JSAPI_MODE = "ACJSAPIMode";
    public static final String SECTION_KEY_RESOURCE_JSAPI_MODE = "jsapiMode";
    public static final String SECTION_KEY_WHITE_LIST = "whiteList";
    public static final String TAG = "IAPConnectPlugin";
    public static final String UNDERSCORE = "_";

    private Constants() {
    }

    static {
        JS_API_LIST.add(JS_API_CHOOSE_CITY);
        JS_API_LIST.add(JS_API_EXIT_APP);
        JS_API_LIST.add(JS_API_GET_APP_TOKEN);
        JS_API_LIST.add(JS_API_GET_AUTH_CODE);
        JS_API_LIST.add(JS_API_GET_COMPONENT_AUTH);
        JS_API_LIST.add("getPaymentCode");
        JS_API_LIST.add(JS_API_GET_SERVER_TIME);
        JS_API_LIST.add(JS_API_GET_SETTING);
        JS_API_LIST.add(JS_API_GET_SITE_INFO);
        JS_API_LIST.add(JS_API_INQUIRE_QUOTE);
        JS_API_LIST.add(JS_API_IS_INSTALLED_APP);
        JS_API_LIST.add("rpc");
        JS_API_LIST.add(JS_API_REGION_RPC);
        JS_API_LIST.add("scan");
        JS_API_LIST.add(JS_API_SIGN_CONTRACT);
        List<String> list = JS_API_LIST;
        Object obj = JS_API_SIGN_CONTRACT;
        list.add("startApp");
        JS_API_LIST.add(JS_API_THIRD_PARTY_AUTH_FOR_AC);
        List<String> list2 = JS_API_LIST;
        Object obj2 = JS_API_THIRD_PARTY_AUTH_FOR_AC;
        list2.add(JS_API_NAVIGATE_TO_BIZ_SCENE);
        JS_API_LIST.add(JS_API_OPEN_SCHEME_WITH_BACKING);
        List<String> list3 = JS_API_LIST;
        Object obj3 = JS_API_OPEN_SCHEME_WITH_BACKING;
        list3.add(JS_API_APPX_RPC);
        JS_API_LIST.add(JS_API_START_BIZ_SERVICE);
        JS_API_LIST.add(JS_API_UPLOAD_APDID_TOKEN);
        List<String> list4 = JS_API_LIST;
        Object obj4 = JS_API_UPLOAD_APDID_TOKEN;
        list4.add(JS_API_AP_DISABLE_JSAPI);
        Map<String, Class<? extends BaseInterceptor>> map = JS_INTERCEPTOR_MAP;
        Object obj5 = JS_API_AP_DISABLE_JSAPI;
        map.put(JS_API_CHOOSE_CITY, Interceptor4chooseCity.class);
        JS_INTERCEPTOR_MAP.put(JS_API_EXIT_APP, Interceptor4exitApp.class);
        JS_INTERCEPTOR_MAP.put(JS_API_GET_APP_TOKEN, Interceptor4getAppToken.class);
        JS_INTERCEPTOR_MAP.put(JS_API_GET_AUTH_CODE, Interceptor4getAuthCode.class);
        JS_INTERCEPTOR_MAP.put(JS_API_GET_COMPONENT_AUTH, Interceptor4getComponentAuth.class);
        JS_INTERCEPTOR_MAP.put(JS_API_GET_OPEN_USER_INFO, Interceptor4getOpenUserInfo.class);
        JS_INTERCEPTOR_MAP.put("getPaymentCode", Interceptor4getPaymentCode.class);
        JS_INTERCEPTOR_MAP.put(JS_API_GET_PHONE_NUMBER, Interceptor4getPhoneNumber.class);
        JS_INTERCEPTOR_MAP.put(JS_API_GET_SERVER_TIME, Interceptor4getServerTime.class);
        JS_INTERCEPTOR_MAP.put(JS_API_GET_SETTING, Interceptor4getSetting.class);
        JS_INTERCEPTOR_MAP.put(JS_API_GET_SITE_INFO, Interceptor4getSiteInfo.class);
        JS_INTERCEPTOR_MAP.put(JS_API_INQUIRE_QUOTE, Interceptor4inquireQuote.class);
        JS_INTERCEPTOR_MAP.put(JS_API_IS_INSTALLED_APP, Interceptor4isInstalledApp.class);
        JS_INTERCEPTOR_MAP.put(JS_API_NAVIGATE_TO_BIZ_SCENE, Interceptor4navigateToBizScene.class);
        JS_INTERCEPTOR_MAP.put(JS_API_PAY_SIGN_CENTER, Interceptor4paySignCenter.class);
        JS_INTERCEPTOR_MAP.put("rpc", Interceptor4rpc.class);
        JS_INTERCEPTOR_MAP.put(JS_API_REGION_RPC, Interceptor4RegionRpc.class);
        JS_INTERCEPTOR_MAP.put("scan", Interceptor4scan.class);
        JS_INTERCEPTOR_MAP.put(obj, Interceptor4signContract.class);
        JS_INTERCEPTOR_MAP.put("startApp", Interceptor4startApp.class);
        JS_INTERCEPTOR_MAP.put(obj2, Interceptor4thirdPartyAuthForAc.class);
        JS_INTERCEPTOR_MAP.put(obj3, Interceptor4openSchemeWithBacking.class);
        JS_INTERCEPTOR_MAP.put(obj4, Interceptor4uploadApdidToken.class);
        JS_INTERCEPTOR_MAP.put(obj5, Interceptor4apDisableJSAPI.class);
    }
}
