package com.iap.ac.android.biz.common.model;

public enum InitErrorCode {
    INITIALIZE_UNKNOWN_EXCEPTION,
    INITIALIZE_AUTHENTICATION_FAILED,
    INITIALIZE_PARAM_ILLEGAL,
    INITIALIZE_INVALID_NETWORK
}
