package com.zoloz.android.phone.zdoc;

public final class R {

    public static final class attr {
        public static int z_background = com.zoloz.builder.R.attr.z_background;
        public static int z_bg = com.zoloz.builder.R.attr.z_bg;
        public static int z_button_font = com.zoloz.builder.R.attr.z_button_font;
        public static int z_custom = com.zoloz.builder.R.attr.z_custom;
        public static int z_left_src = com.zoloz.builder.R.attr.z_left_src;
        public static int z_line_color = com.zoloz.builder.R.attr.z_line_color;
        public static int z_mask_background = com.zoloz.builder.R.attr.z_mask_background;
        public static int z_mask_bottom_margin = com.zoloz.builder.R.attr.z_mask_bottom_margin;
        public static int z_mask_invisible_height = com.zoloz.builder.R.attr.z_mask_invisible_height;
        public static int z_message_view_custom = com.zoloz.builder.R.attr.z_message_view_custom;
        public static int z_position = com.zoloz.builder.R.attr.z_position;
        public static int z_replace_res_array = com.zoloz.builder.R.attr.z_replace_res_array;
        public static int z_replace_str_array = com.zoloz.builder.R.attr.z_replace_str_array;
        public static int z_separate_visibility = com.zoloz.builder.R.attr.z_separate_visibility;
        public static int z_showPress = com.zoloz.builder.R.attr.z_showPress;
        public static int z_text = com.zoloz.builder.R.attr.z_text;
        public static int z_text_color = com.zoloz.builder.R.attr.z_text_color;
        public static int z_textview_font = com.zoloz.builder.R.attr.z_textview_font;
    }

    public static final class bool {
        public static int show_exit_dialog = com.zoloz.builder.R.bool.show_exit_dialog;
        public static int title_bar_left = com.zoloz.builder.R.bool.title_bar_left;
        public static int title_bar_title_center_horizontal = com.zoloz.builder.R.bool.title_bar_title_center_horizontal;
        public static int title_bar_with_line = com.zoloz.builder.R.bool.title_bar_with_line;
        public static int zdoc_frame_corner = com.zoloz.builder.R.bool.zdoc_frame_corner;
    }

    public static final class color {
        public static int brand_text_color = com.zoloz.builder.R.color.brand_text_color;
        public static int dialog_cancel = com.zoloz.builder.R.color.dialog_cancel;
        public static int dialog_message = com.zoloz.builder.R.color.dialog_message;
        public static int dialog_ok = com.zoloz.builder.R.color.dialog_ok;
        public static int dialog_title = com.zoloz.builder.R.color.dialog_title;
        public static int gcash_pinkblue = com.zoloz.builder.R.color.gcash_pinkblue;
        public static int title_back_color = com.zoloz.builder.R.color.title_back_color;
        public static int title_color = com.zoloz.builder.R.color.title_color;
        public static int titlebar_color = com.zoloz.builder.R.color.titlebar_color;
        public static int titlebar_end_color = com.zoloz.builder.R.color.titlebar_end_color;
        public static int titlebar_split_line_color = com.zoloz.builder.R.color.titlebar_split_line_color;
        public static int titlebar_start_color = com.zoloz.builder.R.color.titlebar_start_color;
        public static int z_black = com.zoloz.builder.R.color.z_black;
        public static int z_black_60 = com.zoloz.builder.R.color.z_black_60;
        public static int z_blue = com.zoloz.builder.R.color.z_blue;
        public static int z_grey = com.zoloz.builder.R.color.z_grey;
        public static int z_grey_2 = com.zoloz.builder.R.color.z_grey_2;
        public static int z_grey_3 = com.zoloz.builder.R.color.z_grey_3;
        public static int z_white = com.zoloz.builder.R.color.z_white;
        public static int z_white_50 = com.zoloz.builder.R.color.z_white_50;
        public static int zdoc_confirm_btn_normal_color = com.zoloz.builder.R.color.zdoc_confirm_btn_normal_color;
        public static int zdoc_confirm_btn_press_color = com.zoloz.builder.R.color.zdoc_confirm_btn_press_color;
        public static int zdoc_frame_bg_color = com.zoloz.builder.R.color.zdoc_frame_bg_color;
        public static int zdoc_frame_tips_color = com.zoloz.builder.R.color.zdoc_frame_tips_color;
        public static int zdoc_line_color = com.zoloz.builder.R.color.zdoc_line_color;
        public static int zdoc_line_color_light = com.zoloz.builder.R.color.zdoc_line_color_light;
        public static int zdoc_line_cornor_color = com.zoloz.builder.R.color.zdoc_line_cornor_color;
        public static int zdoc_message_tips_color = com.zoloz.builder.R.color.zdoc_message_tips_color;
        public static int zdoc_message_view_bg_color = com.zoloz.builder.R.color.zdoc_message_view_bg_color;
        public static int zdoc_retake_bg = com.zoloz.builder.R.color.zdoc_retake_bg;
        public static int zdoc_retake_border_color = com.zoloz.builder.R.color.zdoc_retake_border_color;
        public static int zdoc_retake_text_color = com.zoloz.builder.R.color.zdoc_retake_text_color;
        public static int zdoc_submit_bg = com.zoloz.builder.R.color.zdoc_submit_bg;
        public static int zdoc_submit_border_color = com.zoloz.builder.R.color.zdoc_submit_border_color;
        public static int zdoc_submit_text_color = com.zoloz.builder.R.color.zdoc_submit_text_color;
    }

    public static final class dimen {
        public static int dialog_btn_divide = com.zoloz.builder.R.dimen.dialog_btn_divide;
        public static int dialog_btn_height = com.zoloz.builder.R.dimen.dialog_btn_height;
        public static int dialog_btn_margin_left = com.zoloz.builder.R.dimen.dialog_btn_margin_left;
        public static int dialog_btn_margin_top = com.zoloz.builder.R.dimen.dialog_btn_margin_top;
        public static int dialog_btn_text_size = com.zoloz.builder.R.dimen.dialog_btn_text_size;
        public static int dialog_close_btn = com.zoloz.builder.R.dimen.dialog_close_btn;
        public static int dialog_close_btn_margin_top = com.zoloz.builder.R.dimen.dialog_close_btn_margin_top;
        public static int dialog_count_margin_top = com.zoloz.builder.R.dimen.dialog_count_margin_top;
        public static int dialog_count_size = com.zoloz.builder.R.dimen.dialog_count_size;
        public static int dialog_protocal_size = com.zoloz.builder.R.dimen.dialog_protocal_size;
        public static int dialog_subtitle_margin_top = com.zoloz.builder.R.dimen.dialog_subtitle_margin_top;
        public static int dialog_subtitle_size = com.zoloz.builder.R.dimen.dialog_subtitle_size;
        public static int dialog_title_margin_top = com.zoloz.builder.R.dimen.dialog_title_margin_top;
        public static int dialog_title_size = com.zoloz.builder.R.dimen.dialog_title_size;
        public static int font_x_large = com.zoloz.builder.R.dimen.font_x_large;
        public static int message_view_text_content_padding = com.zoloz.builder.R.dimen.message_view_text_content_padding;
        public static int operation_height = com.zoloz.builder.R.dimen.operation_height;
        public static int take_photo_border_size = com.zoloz.builder.R.dimen.take_photo_border_size;
        public static int take_photo_center_inset_size = com.zoloz.builder.R.dimen.take_photo_center_inset_size;
        public static int take_photo_center_size = com.zoloz.builder.R.dimen.take_photo_center_size;
        public static int take_photo_size = com.zoloz.builder.R.dimen.take_photo_size;
        public static int z_dimen_10 = com.zoloz.builder.R.dimen.z_dimen_10;
        public static int z_dimen_15 = com.zoloz.builder.R.dimen.z_dimen_15;
        public static int z_dimen_20 = com.zoloz.builder.R.dimen.z_dimen_20;
        public static int z_dimen_30 = com.zoloz.builder.R.dimen.z_dimen_30;
        public static int z_dimen_300 = com.zoloz.builder.R.dimen.z_dimen_300;
        public static int z_dimen_35 = com.zoloz.builder.R.dimen.z_dimen_35;
        public static int z_dimen_5 = com.zoloz.builder.R.dimen.z_dimen_5;
        public static int z_dimen_60 = com.zoloz.builder.R.dimen.z_dimen_60;
        public static int z_dimen_80 = com.zoloz.builder.R.dimen.z_dimen_80;
        public static int z_text_size_12 = com.zoloz.builder.R.dimen.z_text_size_12;
        public static int z_text_size_15 = com.zoloz.builder.R.dimen.z_text_size_15;
        public static int z_text_size_16 = com.zoloz.builder.R.dimen.z_text_size_16;
        public static int z_text_size_18 = com.zoloz.builder.R.dimen.z_text_size_18;
        public static int z_text_size_23 = com.zoloz.builder.R.dimen.z_text_size_23;
        public static int z_text_size_24 = com.zoloz.builder.R.dimen.z_text_size_24;
    }

    public static final class drawable {
        public static int bar_line = com.zoloz.builder.R.drawable.bar_line;
        public static int btn_normal = com.zoloz.builder.R.drawable.btn_normal;
        public static int btn_pressed = com.zoloz.builder.R.drawable.btn_pressed;
        public static int button_select = com.zoloz.builder.R.drawable.button_select;
        public static int dialog_white_bg = com.zoloz.builder.R.drawable.dialog_white_bg;
        public static int icon_success = com.zoloz.builder.R.drawable.icon_success;
        public static int separate = com.zoloz.builder.R.drawable.separate;
        public static int simple_toast_bg = com.zoloz.builder.R.drawable.simple_toast_bg;
        public static int title_bar_back = com.zoloz.builder.R.drawable.title_bar_back;
        public static int zdoc_confirm_bg = com.zoloz.builder.R.drawable.zdoc_confirm_bg;
        public static int zdoc_retake_bg = com.zoloz.builder.R.drawable.zdoc_retake_bg;
        public static int zdoc_take_photo_btn_bg = com.zoloz.builder.R.drawable.zdoc_take_photo_btn_bg;
        public static int zdoc_titlebar_bg = com.zoloz.builder.R.drawable.zdoc_titlebar_bg;
        public static int zdoc_titlebar_bg_without_line = com.zoloz.builder.R.drawable.zdoc_titlebar_bg_without_line;
    }

    public static final class id {
        public static int body = com.zoloz.builder.R.id.body;
        public static int btn_X = com.zoloz.builder.R.id.btn_X;
        public static int btn_X_label = com.zoloz.builder.R.id.btn_X_label;
        public static int btn_left = com.zoloz.builder.R.id.btn_left;
        public static int btn_ok = com.zoloz.builder.R.id.btn_ok;
        public static int btn_press = com.zoloz.builder.R.id.btn_press;
        public static int btn_right = com.zoloz.builder.R.id.btn_right;
        public static int btn_x = com.zoloz.builder.R.id.btn_x;
        public static int dialog_btn_cancel = com.zoloz.builder.R.id.dialog_btn_cancel;
        public static int dialog_btn_cancel_center = com.zoloz.builder.R.id.dialog_btn_cancel_center;
        public static int dialog_btn_confirm = com.zoloz.builder.R.id.dialog_btn_confirm;
        public static int dialog_buttons = com.zoloz.builder.R.id.dialog_buttons;
        public static int dialog_content = com.zoloz.builder.R.id.dialog_content;
        public static int dialog_content_sub_title = com.zoloz.builder.R.id.dialog_content_sub_title;
        public static int dialog_content_title = com.zoloz.builder.R.id.dialog_content_title;
        public static int dialog_protocol = com.zoloz.builder.R.id.dialog_protocol;
        public static int iv_bar = com.zoloz.builder.R.id.iv_bar;
        public static int iv_left = com.zoloz.builder.R.id.iv_left;
        public static int iv_photo = com.zoloz.builder.R.id.iv_photo;
        public static int iv_right = com.zoloz.builder.R.id.iv_right;
        public static int iv_separate = com.zoloz.builder.R.id.iv_separate;
        public static int layout_mask_view = com.zoloz.builder.R.id.layout_mask_view;
        public static int layout_message = com.zoloz.builder.R.id.layout_message;
        public static int layout_root = com.zoloz.builder.R.id.layout_root;
        public static int layout_titlebar = com.zoloz.builder.R.id.layout_titlebar;
        public static int message = com.zoloz.builder.R.id.message;
        public static int message_opt_layout = com.zoloz.builder.R.id.message_opt_layout;
        public static int protocol = com.zoloz.builder.R.id.protocol;
        public static int remind_text = com.zoloz.builder.R.id.remind_text;
        public static int surface = com.zoloz.builder.R.id.surface;
        public static int tv_branding = com.zoloz.builder.R.id.tv_branding;
        public static int tv_confirm_msg = com.zoloz.builder.R.id.tv_confirm_msg;
        public static int tv_left = com.zoloz.builder.R.id.tv_left;
        public static int tv_main_message = com.zoloz.builder.R.id.tv_main_message;
        public static int tv_right = com.zoloz.builder.R.id.tv_right;
        public static int tv_title = com.zoloz.builder.R.id.tv_title;
        public static int zdoc_capture = com.zoloz.builder.R.id.zdoc_capture;
        public static int zdoc_submit_text = com.zoloz.builder.R.id.zdoc_submit_text;
    }

    public static final class integer {
        public static int titlebar_bg_angle = com.zoloz.builder.R.integer.titlebar_bg_angle;
    }

    public static final class layout {
        public static int general_dialog = com.zoloz.builder.R.layout.general_dialog;
        public static int layout_manual_passport = com.zoloz.builder.R.layout.layout_manual_passport;
        public static int layout_manual_stand_frame = com.zoloz.builder.R.layout.layout_manual_stand_frame;
        public static int layout_message = com.zoloz.builder.R.layout.layout_message;
        public static int layout_progress_dialog = com.zoloz.builder.R.layout.layout_progress_dialog;
        public static int layout_titile_bar = com.zoloz.builder.R.layout.layout_titile_bar;
        public static int layout_upload_success = com.zoloz.builder.R.layout.layout_upload_success;
        public static int passport_half_frame = com.zoloz.builder.R.layout.passport_half_frame;
    }

    public static final class string {
        public static int alert_interrupt_error_msg = com.zoloz.builder.R.string.alert_interrupt_error_msg;
        public static int alert_interrupt_error_title = com.zoloz.builder.R.string.alert_interrupt_error_title;
        public static int alert_timeout_error_msg = com.zoloz.builder.R.string.alert_timeout_error_msg;
        public static int alert_timeout_error_title = com.zoloz.builder.R.string.alert_timeout_error_title;
        public static int btn_exit = com.zoloz.builder.R.string.btn_exit;
        public static int btn_retry = com.zoloz.builder.R.string.btn_retry;
        public static int main_big_frame_msg_default = com.zoloz.builder.R.string.main_big_frame_msg_default;
        public static int main_big_frame_msg_default_back = com.zoloz.builder.R.string.main_big_frame_msg_default_back;
        public static int main_big_frame_msg_default_front = com.zoloz.builder.R.string.main_big_frame_msg_default_front;
        public static int main_message_default = com.zoloz.builder.R.string.main_message_default;
        public static int main_message_default_back = com.zoloz.builder.R.string.main_message_default_back;
        public static int main_message_default_front = com.zoloz.builder.R.string.main_message_default_front;
        public static int network_error_exit = com.zoloz.builder.R.string.network_error_exit;
        public static int network_error_msg = com.zoloz.builder.R.string.network_error_msg;
        public static int network_error_retry = com.zoloz.builder.R.string.network_error_retry;
        public static int network_error_title = com.zoloz.builder.R.string.network_error_title;
        public static int system_error_got_it = com.zoloz.builder.R.string.system_error_got_it;
        public static int system_error_msg = com.zoloz.builder.R.string.system_error_msg;
        public static int system_error_title = com.zoloz.builder.R.string.system_error_title;
        public static int title_back = com.zoloz.builder.R.string.title_back;
        public static int zdoc_blur_msg = com.zoloz.builder.R.string.zdoc_blur_msg;
        public static int zdoc_blur_title = com.zoloz.builder.R.string.zdoc_blur_title;
        public static int zdoc_camera_permission_msg = com.zoloz.builder.R.string.zdoc_camera_permission_msg;
        public static int zdoc_camera_permission_not_allow = com.zoloz.builder.R.string.zdoc_camera_permission_not_allow;
        public static int zdoc_camera_permission_settings = com.zoloz.builder.R.string.zdoc_camera_permission_settings;
        public static int zdoc_camera_permission_title = com.zoloz.builder.R.string.zdoc_camera_permission_title;
        public static int zdoc_capture = com.zoloz.builder.R.string.zdoc_capture;
        public static int zdoc_confirm = com.zoloz.builder.R.string.zdoc_confirm;
        public static int zdoc_dialog_close = com.zoloz.builder.R.string.zdoc_dialog_close;
        public static int zdoc_dialog_retry = com.zoloz.builder.R.string.zdoc_dialog_retry;
        public static int zdoc_expired_document_msg = com.zoloz.builder.R.string.zdoc_expired_document_msg;
        public static int zdoc_expired_document_title = com.zoloz.builder.R.string.zdoc_expired_document_title;
        public static int zdoc_exposure_msg = com.zoloz.builder.R.string.zdoc_exposure_msg;
        public static int zdoc_exposure_title = com.zoloz.builder.R.string.zdoc_exposure_title;
        public static int zdoc_imperfect_msg = com.zoloz.builder.R.string.zdoc_imperfect_msg;
        public static int zdoc_imperfect_title = com.zoloz.builder.R.string.zdoc_imperfect_title;
        public static int zdoc_no_document_msg = com.zoloz.builder.R.string.zdoc_no_document_msg;
        public static int zdoc_no_document_title = com.zoloz.builder.R.string.zdoc_no_document_title;
        public static int zdoc_noface_msg = com.zoloz.builder.R.string.zdoc_noface_msg;
        public static int zdoc_noface_title = com.zoloz.builder.R.string.zdoc_noface_title;
        public static int zdoc_processing = com.zoloz.builder.R.string.zdoc_processing;
        public static int zdoc_retry = com.zoloz.builder.R.string.zdoc_retry;
        public static int zdoc_retry_max_got_it = com.zoloz.builder.R.string.zdoc_retry_max_got_it;
        public static int zdoc_retry_max_msg = com.zoloz.builder.R.string.zdoc_retry_max_msg;
        public static int zdoc_retry_max_title = com.zoloz.builder.R.string.zdoc_retry_max_title;
        public static int zdoc_submit = com.zoloz.builder.R.string.zdoc_submit;
        public static int zdoc_success = com.zoloz.builder.R.string.zdoc_success;
        public static int zdoc_title = com.zoloz.builder.R.string.zdoc_title;
        public static int zdoc_unknow_msg = com.zoloz.builder.R.string.zdoc_unknow_msg;
        public static int zdoc_unknow_title = com.zoloz.builder.R.string.zdoc_unknow_title;
        public static int zdoc_user_cancel_msg = com.zoloz.builder.R.string.zdoc_user_cancel_msg;
        public static int zdoc_user_cancel_quit = com.zoloz.builder.R.string.zdoc_user_cancel_quit;
        public static int zdoc_user_cancel_stay = com.zoloz.builder.R.string.zdoc_user_cancel_stay;
        public static int zdoc_user_cancel_title = com.zoloz.builder.R.string.zdoc_user_cancel_title;
        public static int zdoc_wrong_document_msg = com.zoloz.builder.R.string.zdoc_wrong_document_msg;
        public static int zdoc_wrong_document_title = com.zoloz.builder.R.string.zdoc_wrong_document_title;
        public static int zoloz_brand = com.zoloz.builder.R.string.zoloz_brand;
    }

    public static final class style {
        public static int dialog_style = com.zoloz.builder.R.style.dialog_style;
        public static int process_style = com.zoloz.builder.R.style.process_style;
    }

    public static final class styleable {
        public static int[] CustomButton = com.zoloz.builder.R.styleable.CustomButton;
        public static int CustomButton_z_button_font = com.zoloz.builder.R.styleable.CustomButton_z_button_font;
        public static int[] CustomTextView = com.zoloz.builder.R.styleable.CustomTextView;
        public static int CustomTextView_z_textview_font = com.zoloz.builder.R.styleable.CustomTextView_z_textview_font;
        public static int[] DefaultMaskView = com.zoloz.builder.R.styleable.DefaultMaskView;
        public static int DefaultMaskView_z_line_color = com.zoloz.builder.R.styleable.DefaultMaskView_z_line_color;
        public static int DefaultMaskView_z_mask_background = com.zoloz.builder.R.styleable.DefaultMaskView_z_mask_background;
        public static int DefaultMaskView_z_mask_bottom_margin = com.zoloz.builder.R.styleable.DefaultMaskView_z_mask_bottom_margin;
        public static int DefaultMaskView_z_mask_invisible_height = com.zoloz.builder.R.styleable.DefaultMaskView_z_mask_invisible_height;
        public static int[] MessageView = com.zoloz.builder.R.styleable.MessageView;
        public static int MessageView_z_message_view_custom = com.zoloz.builder.R.styleable.MessageView_z_message_view_custom;
        public static int MessageView_z_showPress = com.zoloz.builder.R.styleable.MessageView_z_showPress;
        public static int[] ReplaceTextToImgTextView = com.zoloz.builder.R.styleable.ReplaceTextToImgTextView;
        public static int ReplaceTextToImgTextView_z_replace_res_array = com.zoloz.builder.R.styleable.ReplaceTextToImgTextView_z_replace_res_array;
        public static int ReplaceTextToImgTextView_z_replace_str_array = com.zoloz.builder.R.styleable.ReplaceTextToImgTextView_z_replace_str_array;
        public static int[] TitleBar = com.zoloz.builder.R.styleable.TitleBar;
        public static int TitleBar_z_background = com.zoloz.builder.R.styleable.TitleBar_z_background;
        public static int TitleBar_z_bg = com.zoloz.builder.R.styleable.TitleBar_z_bg;
        public static int TitleBar_z_custom = com.zoloz.builder.R.styleable.TitleBar_z_custom;
        public static int TitleBar_z_left_src = com.zoloz.builder.R.styleable.TitleBar_z_left_src;
        public static int TitleBar_z_position = com.zoloz.builder.R.styleable.TitleBar_z_position;
        public static int TitleBar_z_separate_visibility = com.zoloz.builder.R.styleable.TitleBar_z_separate_visibility;
        public static int TitleBar_z_text = com.zoloz.builder.R.styleable.TitleBar_z_text;
        public static int TitleBar_z_text_color = com.zoloz.builder.R.styleable.TitleBar_z_text_color;
    }
}
