package o;

import id.dana.domain.feeds.model.FeedsSource;

public final class pageScroll {
    public final String getMax;
    private final int getMin;
    public final int length;
    public final String setMin;

    public pageScroll(int i, String str, String str2) {
        int i2;
        if (str != null) {
            this.length = i;
            this.setMin = str;
            this.getMax = str2;
            int hashCode = str.hashCode() * 31 * 31;
            if (str2 == null) {
                i2 = 0;
            } else {
                i2 = str2.hashCode();
            }
            this.getMin = hashCode + (i2 * 31) + this.length;
            return;
        }
        throw new IllegalArgumentException("reference can't be null");
    }

    /* JADX WARNING: Code restructure failed: missing block: B:14:0x0028, code lost:
        r2 = r4.getMax;
        r5 = r5.getMax;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:9:0x001a, code lost:
        r2 = r4.setMin;
        r3 = r5.setMin;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final boolean equals(java.lang.Object r5) {
        /*
            r4 = this;
            r0 = 1
            if (r4 != r5) goto L_0x0004
            return r0
        L_0x0004:
            r1 = 0
            if (r5 == 0) goto L_0x0037
            java.lang.Class r2 = r4.getClass()
            java.lang.Class r3 = r5.getClass()
            if (r2 == r3) goto L_0x0012
            goto L_0x0037
        L_0x0012:
            o.pageScroll r5 = (o.pageScroll) r5
            int r2 = r4.length
            int r3 = r5.length
            if (r2 != r3) goto L_0x0037
            java.lang.String r2 = r4.setMin
            java.lang.String r3 = r5.setMin
            if (r2 == r3) goto L_0x0028
            if (r2 == 0) goto L_0x0037
            boolean r2 = r2.equals(r3)
            if (r2 == 0) goto L_0x0037
        L_0x0028:
            java.lang.String r2 = r4.getMax
            java.lang.String r5 = r5.getMax
            if (r2 == r5) goto L_0x0036
            if (r2 == 0) goto L_0x0037
            boolean r5 = r2.equals(r5)
            if (r5 == 0) goto L_0x0037
        L_0x0036:
            return r0
        L_0x0037:
            return r1
        */
        throw new UnsupportedOperationException("Method not decompiled: o.pageScroll.equals(java.lang.Object):boolean");
    }

    public final int hashCode() {
        return this.getMin;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("TransitionId{");
        sb.append("\"");
        sb.append(this.setMin);
        sb.append("\", ");
        int i = this.length;
        if (i == 1) {
            sb.append(FeedsSource.GLOBAL);
        } else if (i == 2) {
            sb.append("SCOPED(");
            sb.append(this.getMax);
            sb.append(")");
        } else if (i == 3) {
            sb.append("AUTOGENERATED");
        }
        sb.append("}");
        return sb.toString();
    }
}
